version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./dir/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
      #command: -f /mnt/locust/locustfile.py --master -H http://localhost:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./dir/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

